// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fosflnuwxusuuxnnqvxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvc2ZsbnV3eHVzdXV4bm5xdnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDk5MzEsImV4cCI6MjA3NDAyNTkzMX0.IVnnRsAe0DFJT9uK7MZFfjqMm62BH5ud_dUWRz_GMJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});